### ISSUE TITLE
Week 9 exercise is ready to review

### ISSUE THREAD

**Issue by Carlos-Leon98** [Carlos-Leon98/Week9-activity#1]
Hi @pawaitemadisoncollege,

Here I send the results of exercise for week 9.

Get All

<img width="1438" alt="Week9-getAll" src="https://github.com/Carlos-Leon98/Week9-activity/assets/69998153/34ab0ae1-cfa3-4724-a578-086a6db10314">

Get By Id

<img width="1436" alt="Week9-getById" src="https://github.com/Carlos-Leon98/Week9-activity/assets/69998153/d8e0f1c0-1e7c-4f79-a189-8cb170134004">

What were your key learning points/takeaways? - Always check the credentials in the hibernate.cfg.xml for the database
What challenged you? - Not figuring out why I wasn't able to read the response
What problems did you solve and what resources did you use to solve them? - With a lot of help of StackOverflow, basically my issue was that I wasn't converting to json my objects before sending the request.

Thank you,
Carlos Leon Rivas

**Comment by pawaitemadisoncollege** [comment]
Hi @Carlos-Leon98! Sorry for the very late review on this work. This meets the requirements for the week 9 exercise - you did a good job following best practices for naming the restful resources!

**Comment by Carlos-Leon98** [comment]
@pawaitemadisoncollege Thank you!! I am closing this issue.
